{% set version = "3.3.3" %}
{% set build_number= "1" %}

package:
  name: ffmpeg
  version: {{ version }}

source:
  fn: ffmpeg-{{ version }}.tar.gz  # [not win]
  url: https://ffmpeg.org/releases/ffmpeg-{{ version }}.tar.gz  # [not win]
  sha256: 66000646f487496bc33cf0ab72ca1cd4c8bd52f295c45428ed69735925a2bf3c  # [not win]

  fn: ffmpeg-{{ version }}-win32-shared.zip  # [win32]
  url: https://ffmpeg.zeranoe.com/builds/win32/shared/ffmpeg-{{ version }}-win32-shared.zip  # [win32]
  sha256: 556c4520dfd2189b8b74ca8409f97ab74978bcba8f9402552f4b8845a4917b33  # [win32]

  fn: ffmpeg-{{ version }}-win64-shared.zip  # [win64]
  url: https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-{{ version }}-win64-shared.zip  # [win64]
  sha256: 7bd11db97d8b26e5593af9686fe35af77a7e65bb35dedd2cc0d2ddc7ea6485b7  # [win64]

build:
  number: {{ build_number }}
  string: gpl_{{ build_number }}

requirements:
  build:
    - toolchain    # [not win]
    - pkg-config   # [not win]
    - libtool      # [not win]
    - yasm         # [not win]
    - bzip2 1.0.*  # [not win]
    - libiconv 1.15   # [not win]
    - x264 1!152.*         # [not win]
    - zlib 1.2.*   # [not win]
#    - freetype     # [not win]
    - 7za          # [win]
    - curl         # [win]
    - openssl      # [win]
  run:
#    - freetype     # [not win]
    - bzip2 1.0.*  # [not win]
    - libiconv 1.15     # [not win]
    - x264 1!152.*         # [not win]
    - zlib 1.2.*   # [not win]

test:
  commands:
    - ffmpeg --help
    - ffmpeg -codecs | grep "DEVI.S zlib"  # [unix]
    # Verify dynamic libraries on all systems
    {% set ffmpeg_libs = [
        "avcodec",
        "avdevice",
        "swresample",
        "postproc",
        "avfilter",
        "swresample",
        "avcodec",
        "avformat",
        "swscale",
        "avresample"
    ] %}
    {% for each_ffmpeg_lib in ffmpeg_libs %}
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}.so     # [linux]
    {% endfor %}

about:
  home: http://www.ffmpeg.org/
  license: GPL 2
  license_file: COPYING.GPLv2  # [unix]
  summary: Cross-platform solution to record, convert and stream audio and video.

extra:
  original-recipe-maintainers:
    - danielballan
    - jakirkham
    - 183amir
    - caspervdw
    - patricksnape
  recipe-maintainers:
    - sdvillal
